import '@mdi/font/css/materialdesignicons.css';
import {
  VAlert,
  VApp,
  VAppBar,
  VAvatar,
  VBtn,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VChipGroup,
  VCol,
  VContainer,
  VDatePicker,
  VDialog,
  VDivider,
  VFooter,
  VForm,
  VIcon,
  VLayout,
  VList,
  VListItem,
  VListItemTitle,
  VMenu,
  VProgressCircular,
  VProgressLinear,
  VRow,
  VSelect,
  VFileInput,
  VCardItem,
  VSkeletonLoader,
  VSpacer,
  VStepper,
  VStepperHeader,
  VStepperItem,
  VStepperWindow,
  VStepperWindowItem,
  VTable,
  VTextarea,
  VTextField,
  VToolbar,
  VToolbarTitle
} from 'vuetify/components';
import * as directives from 'vuetify/directives';
import { createVuetify } from 'vuetify';
import 'vuetify/styles'; // Base styles/CSS Reset

export default new createVuetify({
  theme: {
    light: true,
    dark: false
  },
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VChipGroup,
    VCol,
    VContainer,
    VDatePicker,
    VDialog,
    VDivider,
    VFooter,
    VForm,
    VIcon,
    VLayout,
    VList,
    VListItem,
    VListItemTitle,
    VMenu,
    VProgressCircular,
    VProgressLinear,
    VRow,
    VSelect,
    VFileInput,
    VCardItem,
    VSkeletonLoader,
    VSpacer,
    VStepper,
    VStepperHeader,
    VStepperItem,
    VStepperWindow,
    VStepperWindowItem,
    VTable,
    VTextarea,
    VTextField,
    VToolbar,
    VToolbarTitle
  },
  directives
});
