---
apiVersion: v1
kind: Template
labels:
    template: "${SERVICE_NAME}-template"
metadata:
    name: "${SERVICE_NAME}-${JOB_NAME}-bc"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${SERVICE_NAME}-${JOB_NAME}"
    name: "${SERVICE_NAME}-${JOB_NAME}"
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${SERVICE_NAME}-${JOB_NAME}"
    name: "${SERVICE_NAME}-${JOB_NAME}-${GIT_REF}"
  spec:
    completionDeadlineSeconds: 800
    successfulBuildsHistoryLimit: 3
    failedBuildsHistoryLimit: 3
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${SERVICE_NAME}-${JOB_NAME}:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 500m
        memory: 500m
      limits:
        cpu: 2500m
        memory: 2Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: "${CONTEXT_DIR}"
      git:
        ref: ${SOURCE_REPO_REF}
        uri: "${SOURCE_REPO_URL}"
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: '2'
        - name: NPM_CONFIG_LOGLEVEL
          value: notice
      type: Docker
parameters:
- name: SERVICE_NAME
  description: Name of service to build
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: SOURCE_REPO_REF
  description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
  required: true
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
- name:  CONTEXT_DIR
  description: Location of application root directory
  required: true
- name: GIT_REF
  description: Git branch where source code is located
  value: 'master'
  required: false
