---
apiVersion: v1
kind: Template
labels: 
	template: student-profile-e2e-pipeline-template
metadata: 
	name: student-profile-e2e-pipeline-template
objects:
- apiVersion: v1
	kind: BuildConfig
	metadata: 
		name: "student-profile-e2e-master-pipeline"
	spec:
		source:
			git:
				ref: master
				uri: "https://github.com/bcgov/EDUC-STUDENT-PROFILE"
		strategy:
			jenkinsPipelineStrategy:
				jenkinsfilePath: tools/jenkins/e2e-Jenkinsfile